export const contactEmail = "xpaolomarzullo@gmail.com"

export const navItems = [
  { label: "Home", href: "/", status: "attiva" },
  { label: "My World", href: "/my-world", status: "attiva" },
  { label: "Pesci", href: "/pesci", status: "galleria" },
  { label: "Conchiglie", href: "/conchiglie", status: "galleria" },
  { label: "Fuori Catalogo", href: "/fuori-catalogo", status: "galleria" },
  { label: "Vetrina", href: "/vetrina", status: "diario" },
]

export const pages = {
  myWorld: {
    title: "My World",
    eyebrow: "Paolo Marzullo",
    intro:
      "Datemi un legno consumato dal mare e con la fantasia e la manualità vi restituirò un pesce colorato.",
    body: [
      "Paolo Marzullo",
      "Sono nato a Livorno nel lontano 1953 e principalmente ho fatto il ricercatore in ambito cardiovascolare raggiungendo ottimi traguardi professionali. Nel tempo libero ho praticato diversi sport senza pensare all’arte fino al 2005 quando ho assemblato pochi legni di mare con tinta, rivetti e pignoni creando il mio pesce #1. Poco più di uno scherzo, ma da questo punto in poi la fantasia, la ricerca della forma e del cromatismo e l’impiego dei più svariati materiali hanno portato a molti più pesci, diverse mostre e tanto apprezzamento non solo dagli amici.",
      "Chi guarda le mie opere non resta indifferente, è questa la ricompensa maggiore per un artista. Non solo pesci ma anche orecchini, conchiglie, galline, lampade, azulejos: di tutto un po’, fatti per piacere o almeno per sembrare cose belle. Buona visione!",
      "I was born in Livorno in 1953 and I have worked as medical doctor in the field of cardiovascular research. I have practiced swimming, skiing, motocross, hunting and fishing with little interest in arts until 2005, when I assembled my fish #1. Ever since fantasy, chromatism and use of many different materials have lead to more than 120 fishes, exhibitions and appreciation from those who look at my creations. Not only fish but also shells, hens, earrings, lamps, tiles: all done to appear, at least, as beautiful things. Enjoy the visit!",
    ],
    gallery: [
      { src: "/images/legnidimare/original/my-world-01.png", alt: "Schermata 2021-11-17 alle 14.43.44" },
    ],
  },
  pesci: {
    title: "Pesci",
    eyebrow: "Galleria principale",
    intro:
      "Questa sezione include in ordine cronologico tutti i miei pesci realizzati con legno di mare e con altri materiali a partire dal 2005.",
    body: [
      "Il n. 100 è stato realizzato con la tecnica del mosaico trencadís; per altri pesci ho impiegato plexiglass, plastica, seme, fiches e altri materiali.",
      "Il materiale dominante è sempre il legno stagionato dal tempo e corroso dal mare.",
    ],
    gallery: [
      { src: "/images/legnidimare/original/pesci-001.jpg", alt: "CERNIA" },
      { src: "/images/legnidimare/original/pesci-002.jpg", alt: "CAPONE (o Lampuga)" },
      { src: "/images/legnidimare/original/pesci-003.jpg", alt: "ABSTRACT" },
      { src: "/images/legnidimare/original/pesci-004.jpg", alt: "CIVETTA" },
      { src: "/images/legnidimare/original/pesci-005.jpg", alt: "RICCIO" },
      { src: "/images/legnidimare/original/pesci-006.jpg", alt: "TROMBETTA" },
      { src: "/images/legnidimare/original/pesci-007.jpg", alt: "NIVOLA" },
      { src: "/images/legnidimare/original/pesci-008.jpg", alt: "BALENOTTERA PLEXI" },
      { src: "/images/legnidimare/original/pesci-009.jpg", alt: "BALENOTTERA DAS" },
      { src: "/images/legnidimare/original/pesci-010.jpg", alt: "CERNIA DAS" },
      { src: "/images/legnidimare/original/pesci-011.jpg", alt: "Nuovo Ghiozzo Semato \"bocca rossa\"" },
      { src: "/images/legnidimare/original/pesci-012.jpg", alt: "ROSSETTO" },
      { src: "/images/legnidimare/original/pesci-013.jpg", alt: "M.A.S." },
      { src: "/images/legnidimare/original/pesci-014.jpg", alt: "GHOST" },
      { src: "/images/legnidimare/original/pesci-015.jpg", alt: "CAPODOGLIO GROSSO" },
      { src: "/images/legnidimare/original/pesci-016.jpg", alt: "CALAMARO" },
      { src: "/images/legnidimare/original/pesci-017.jpg", alt: "TOTANO" },
      { src: "/images/legnidimare/original/pesci-018.jpg", alt: "CAPODOGLIO" },
      { src: "/images/legnidimare/original/pesci-019.jpg", alt: "PANCHINA " },
      { src: "/images/legnidimare/original/pesci-020.jpg", alt: "CHIMERA MOSTRUOSA II" },
      { src: "/images/legnidimare/original/pesci-021.jpg", alt: "LAMPUGA" },
      { src: "/images/legnidimare/original/pesci-022.jpg", alt: "COLORI" },
      { src: "/images/legnidimare/original/pesci-023.jpg", alt: "PAVONINA II" },
      { src: "/images/legnidimare/original/pesci-024.jpg", alt: "LUNA" },
      { src: "/images/legnidimare/original/pesci-025.jpg", alt: "DIRETMUS ARGENTEUS" },
      { src: "/images/legnidimare/original/pesci-026.jpg", alt: "OLIVELLO APOTROPAICO" },
      { src: "/images/legnidimare/original/pesci-027.jpg", alt: "PEPERONCINO" },
      { src: "/images/legnidimare/original/pesci-028.jpg", alt: "PERCA VIRALE" },
      { src: "/images/legnidimare/original/pesci-029.jpg", alt: "BLUE RAY Senegambia" },
      { src: "/images/legnidimare/original/pesci-030.jpg", alt: "Tarlato" },
      { src: "/images/legnidimare/original/pesci-031.jpg", alt: "DRAGONCELLO MACCHIATO" },
      { src: "/images/legnidimare/original/pesci-032.jpg", alt: "ORATA TRENCADIS" },
      { src: "/images/legnidimare/original/pesci-033.jpg", alt: "PESCE TRONCO" },
      { src: "/images/legnidimare/original/pesci-034.jpg", alt: "LUCERTOLA" },
      { src: "/images/legnidimare/original/pesci-035.jpg", alt: "ALACCIA" },
      { src: "/images/legnidimare/original/pesci-036.jpg", alt: "PRAIO  MATERICO" },
      { src: "/images/legnidimare/original/pesci-037.jpg", alt: "DRAGONCELLO TURCHESE" },
      { src: "/images/legnidimare/original/pesci-038.jpg", alt: "SUCCIASCOGLIO SU TUFO" },
      { src: "/images/legnidimare/original/pesci-039.jpg", alt: "RESINATO II" },
      { src: "/images/legnidimare/original/pesci-040.jpg", alt: "LIGHTFISH II" },
      { src: "/images/legnidimare/original/pesci-041.jpg", alt: "Lighfish" },
      { src: "/images/legnidimare/original/pesci-042.jpg", alt: "Pesce TOPO" },
      { src: "/images/legnidimare/original/pesci-043.jpg", alt: "TAMERFISH" },
      { src: "/images/legnidimare/original/pesci-044.jpg", alt: "LEGNI ANTICHI CERNIATI" },
      { src: "/images/legnidimare/original/pesci-045.jpg", alt: "PESCE MAJORE" },
      { src: "/images/legnidimare/original/pesci-046.jpg", alt: "SUGHERO" },
      { src: "/images/legnidimare/original/pesci-047.jpg", alt: "acciugona 1" },
      { src: "/images/legnidimare/original/pesci-048.jpg", alt: "RESINATO" },
      { src: "/images/legnidimare/original/pesci-049.jpg", alt: "VORACE \"SOFT\"" },
      { src: "/images/legnidimare/original/pesci-050.jpg", alt: "Chimera Mostruosa" },
      { src: "/images/legnidimare/original/pesci-051.jpg", alt: "FLAG Rockfish" },
      { src: "/images/legnidimare/original/pesci-052.jpg", alt: "AGUGLIA II" },
      { src: "/images/legnidimare/original/pesci-053.jpg", alt: "CAPODOGLIO 3D" },
      { src: "/images/legnidimare/original/pesci-054.jpg", alt: "Kelp Greenling" },
      { src: "/images/legnidimare/original/pesci-055.jpg", alt: "senza titolo-1" },
      { src: "/images/legnidimare/original/pesci-056.jpg", alt: "CALIFORNIA SHEEPHEAD" },
      { src: "/images/legnidimare/original/pesci-057.jpg", alt: "Spinachia Spinachia" },
      { src: "/images/legnidimare/original/pesci-058.jpg", alt: "Murena 59" },
      { src: "/images/legnidimare/original/pesci-059.jpg", alt: "Donzella Pavonina" },
      { src: "/images/legnidimare/original/pesci-060.jpg", alt: "San Pietro decollato" },
      { src: "/images/legnidimare/original/pesci-061.jpg", alt: "s pietro grigio rivisto" },
      { src: "/images/legnidimare/original/pesci-062.jpg", alt: "VELA" },
      { src: "/images/legnidimare/original/pesci-063.jpg", alt: "vorace mod. 946" },
      { src: "/images/legnidimare/original/pesci-064.jpg", alt: "metamorfosi" },
      { src: "/images/legnidimare/original/pesci-065.jpg", alt: "LISCA" },
      { src: "/images/legnidimare/original/pesci-066.jpg", alt: "GHIOZZO BOCCA ROSSA " },
      { src: "/images/legnidimare/original/pesci-067.jpg", alt: "BALENOTTERA MINORE" },
      { src: "/images/legnidimare/original/pesci-068.png", alt: "CAPOGRIGIO" },
      { src: "/images/legnidimare/original/pesci-069.jpg", alt: "MEGATTERAZ" },
      { src: "/images/legnidimare/original/pesci-070.jpg", alt: "CAPODOGLI  RAZZATI" },
      { src: "/images/legnidimare/original/pesci-071.jpg", alt: "SQUALO BALENA" },
      { src: "/images/legnidimare/original/pesci-072.jpg", alt: "CAPOD" },
      { src: "/images/legnidimare/original/pesci-073.jpg", alt: "I MAGNICI SETTE" },
      { src: "/images/legnidimare/original/pesci-074.jpg", alt: "PASSAGGIO DI AGUGLIA" },
      { src: "/images/legnidimare/original/pesci-075.jpg", alt: "MOBY TOMO" },
      { src: "/images/legnidimare/original/pesci-076.jpg", alt: "GUIZZO DI AMIA" },
      { src: "/images/legnidimare/original/pesci-077.jpg", alt: "TAGLIERE" },
      { src: "/images/legnidimare/original/pesci-078.jpg", alt: "PASSAGGIO DI AGUGLIE IMPERIALI" },
      { src: "/images/legnidimare/original/pesci-079.jpg", alt: "SUCCIASCOGLIO" },
      { src: "/images/legnidimare/original/pesci-080.jpg", alt: "CODA DI STELLA" },
      { src: "/images/legnidimare/original/pesci-081.jpg", alt: "SOGLIOLA OCCHIUTA" },
      { src: "/images/legnidimare/original/pesci-082.jpg", alt: "SCORPIONE EXPO 3D" },
      { src: "/images/legnidimare/original/pesci-083.jpg", alt: "BAVOSA CON L" },
      { src: "/images/legnidimare/original/pesci-084.jpg", alt: "GALLINELLA" },
      { src: "/images/legnidimare/original/pesci-085.jpg", alt: "LIOCORNO" },
      { src: "/images/legnidimare/original/pesci-086.jpg", alt: "BARRACUDA" },
      { src: "/images/legnidimare/original/pesci-087.jpg", alt: "BAVOSA ROSSA" },
      { src: "/images/legnidimare/original/pesci-088.jpg", alt: "DRAGONCELLO" },
      { src: "/images/legnidimare/original/pesci-089.jpg", alt: "diapositiva43" },
      { src: "/images/legnidimare/original/pesci-090.jpg", alt: "SCORFANO" },
      { src: "/images/legnidimare/original/pesci-091.jpg", alt: "TONNO PINNA GIALLA" },
      { src: "/images/legnidimare/original/pesci-092.jpg", alt: "PESCE PALLA SADO MASO" },
      { src: "/images/legnidimare/original/pesci-093.jpg", alt: "BAVOSA COMUNE" },
      { src: "/images/legnidimare/original/pesci-094.jpg", alt: "PESCE TOPO CON CODA DORATA" },
      { src: "/images/legnidimare/original/pesci-095.jpg", alt: "GHIOZZO" },
      { src: "/images/legnidimare/original/pesci-096.jpg", alt: "ISO" },
      { src: "/images/legnidimare/original/pesci-097.jpg", alt: "PETTINE" },
      { src: "/images/legnidimare/original/pesci-098.jpg", alt: "LAMPUGA" },
      { src: "/images/legnidimare/original/pesci-099.jpg", alt: "SQUALO ARTICOLATO" },
      { src: "/images/legnidimare/original/pesci-100.jpg", alt: "PARABLENIUS GATTORUGINE" },
    ],
  },
  conchiglie: {
    title: "Conchiglie",
    eyebrow: "Galleria",
    intro:
      "Nate per caso da una conchiglia rotta, questa raccolta include diversi tipi di conchiglie ammezzate con legno e plexiglass.",
    body: [
      "Ho utilizzato sia legni rari come palissandro e teak che meno nobili come frassino, noce e larice.",
      "Insieme alle conchiglie sono presentati gli induttori di sogno a me tanto cari, veri sonniferi naturali con le istruzioni d’uso. Attenzione: sognerete molto ma non potrete scegliere la tipologia.",
    ],
    gallery: [
      { src: "/images/legnidimare/original/conchiglie-001.jpg", alt: "conchiglia teak a bordo dorato con base acrilica. 18x12x6 2023" },
      { src: "/images/legnidimare/original/conchiglie-002.jpg", alt: "Bambu" },
      { src: "/images/legnidimare/original/conchiglie-003.jpg", alt: "Cuboidi RGB, 2023" },
      { src: "/images/legnidimare/original/conchiglie-004.jpg", alt: "Capodoglio verde con coda dorata, 11 cm, 2023" },
      { src: "/images/legnidimare/original/conchiglie-005.jpg", alt: "Conchiglia di Mussolo, 2023" },
      { src: "/images/legnidimare/original/conchiglie-006.jpg", alt: "Balene coda dorata da stampo unico, 13 cm. 2023" },
      { src: "/images/legnidimare/original/conchiglie-007.jpg", alt: "Cuboide brigantino. Legno di teak 7x3x4 cm 2023" },
      { src: "/images/legnidimare/original/conchiglie-008.jpg", alt: "20221209_234641" },
      { src: "/images/legnidimare/original/conchiglie-009.jpg", alt: "20221209_234759" },
      { src: "/images/legnidimare/original/conchiglie-010.jpg", alt: "ceta" },
      { src: "/images/legnidimare/original/conchiglie-011.jpg", alt: "20221207_195036" },
      { src: "/images/legnidimare/original/conchiglie-012.jpg", alt: "20221204_161146" },
      { src: "/images/legnidimare/original/conchiglie-013.jpg", alt: "vertebra3 06-21" },
      { src: "/images/legnidimare/original/conchiglie-014.jpg", alt: "20211112_211220" },
      { src: "/images/legnidimare/original/conchiglie-015.jpg", alt: "20221202_165850" },
      { src: "/images/legnidimare/original/conchiglie-016.jpg", alt: "3 conchiglie" },
      { src: "/images/legnidimare/original/conchiglie-017.jpg", alt: "granchi port" },
      { src: "/images/legnidimare/original/conchiglie-018.jpg", alt: "14" },
      { src: "/images/legnidimare/original/conchiglie-019.jpg", alt: "13" },
      { src: "/images/legnidimare/original/conchiglie-020.jpg", alt: "13" },
      { src: "/images/legnidimare/original/conchiglie-021.jpg", alt: "12" },
      { src: "/images/legnidimare/original/conchiglie-022.jpg", alt: "11" },
      { src: "/images/legnidimare/original/conchiglie-023.jpg", alt: "10" },
      { src: "/images/legnidimare/original/conchiglie-024.jpg", alt: "9" },
      { src: "/images/legnidimare/original/conchiglie-025.jpg", alt: "cuore coccio" },
      { src: "/images/legnidimare/original/conchiglie-026.jpg", alt: "corallo buggerru" },
      { src: "/images/legnidimare/original/conchiglie-027.jpg", alt: "9" },
      { src: "/images/legnidimare/original/conchiglie-028.jpg", alt: "7" },
      { src: "/images/legnidimare/original/conchiglie-029.jpg", alt: "6" },
      { src: "/images/legnidimare/original/conchiglie-030.jpg", alt: "5" },
      { src: "/images/legnidimare/original/conchiglie-031.jpg", alt: "4" },
      { src: "/images/legnidimare/original/conchiglie-032.jpg", alt: "3" },
      { src: "/images/legnidimare/original/conchiglie-033.jpg", alt: "2" },
      { src: "/images/legnidimare/original/conchiglie-034.jpg", alt: "1" },
      { src: "/images/legnidimare/original/conchiglie-035.jpg", alt: "istruzioni per sognare" },
      { src: "/images/legnidimare/original/conchiglie-036.jpg", alt: "Conchiglie ammezzate" },
      { src: "/images/legnidimare/original/conchiglie-037.jpg", alt: "dentatura di orata" },
      { src: "/images/legnidimare/original/conchiglie-038.jpg", alt: "art deco" },
      { src: "/images/legnidimare/original/conchiglie-039.jpg", alt: "Conchiglia ammezzata n.6" },
      { src: "/images/legnidimare/original/conchiglie-040.jpg", alt: "cetacei" },
      { src: "/images/legnidimare/original/conchiglie-041.jpg", alt: "fermacarte olivo e resina" },
      { src: "/images/legnidimare/original/conchiglie-042.jpg", alt: "Conchiglia ammezzata n.6" },
      { src: "/images/legnidimare/original/conchiglie-043.jpg", alt: "cranio di dentice" },
      { src: "/images/legnidimare/original/conchiglie-044.jpg", alt: "Conchiglia ammezzata n.5" },
      { src: "/images/legnidimare/original/conchiglie-045.jpg", alt: "Conchiglia ammezzata n.4" },
      { src: "/images/legnidimare/original/conchiglie-046.jpg", alt: "Conchiglia ammezzata n.3" },
      { src: "/images/legnidimare/original/conchiglie-047.jpg", alt: "Conchiglia ammezzata n.2" },
      { src: "/images/legnidimare/original/conchiglie-048.jpg", alt: "Conchiglia ammezzata n.1" },
    ],
  },
  fuoriCatalogo: {
    title: "Fuori Catalogo",
    eyebrow: "Oggetti diversi",
    intro:
      "Questa parte raccoglie svariati oggetti nati sempre dall’incontro della mia creatività con diversi materiali.",
    body: [
      "Si va dalle galline in resina, alle azulejos e alla piccola gioielleria, dagli alberelli di Natale alle lampade.",
      "Scoprire queste opere richiede sicuramente più fantasia per l’ospite rispetto a quella dell’artista.",
    ],
    gallery: [
      { src: "/images/legnidimare/original/fuori-catalogo-001.jpg", alt: "poster legni 2021 " },
      { src: "/images/legnidimare/original/fuori-catalogo-002.jpg", alt: "orologio galline 02-21" },
      { src: "/images/legnidimare/original/fuori-catalogo-003.jpg", alt: "codedimare 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-004.jpg", alt: "20220608_222913" },
      { src: "/images/legnidimare/original/fuori-catalogo-005.jpg", alt: "20220608_221056" },
      { src: "/images/legnidimare/original/fuori-catalogo-006.jpg", alt: "20220601_205600" },
      { src: "/images/legnidimare/original/fuori-catalogo-007.jpg", alt: "como costanza 06-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-008.jpg", alt: "olmo" },
      { src: "/images/legnidimare/original/fuori-catalogo-009.jpg", alt: "granceola 06-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-010.jpg", alt: "dsc01250" },
      { src: "/images/legnidimare/original/fuori-catalogo-011.jpg", alt: "20221202_165058" },
      { src: "/images/legnidimare/original/fuori-catalogo-012.jpg", alt: "20221204_162601" },
      { src: "/images/legnidimare/original/fuori-catalogo-013.jpg", alt: "20221207_194841" },
      { src: "/images/legnidimare/original/fuori-catalogo-014.jpg", alt: "20221207_194810" },
      { src: "/images/legnidimare/original/fuori-catalogo-015.jpg", alt: "20221202_165551" },
      { src: "/images/legnidimare/original/fuori-catalogo-016.jpg", alt: "20221202_165800" },
      { src: "/images/legnidimare/original/fuori-catalogo-017.jpg", alt: "3 conchiglie" },
      { src: "/images/legnidimare/original/fuori-catalogo-018.jpg", alt: "predatori 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-019.jpg", alt: "tavola giulia 06-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-020.jpg", alt: "piuma 11-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-021.jpg", alt: "cinema 2020" },
      { src: "/images/legnidimare/original/fuori-catalogo-022.jpg", alt: "pendentif 04-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-023.jpg", alt: "coppia taglieri 03-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-024.jpg", alt: "Orecchini radica olmo 07-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-025.jpg", alt: "portagioie 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-026.jpg", alt: "piccole stelle 03-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-027.jpg", alt: "ELE 04-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-028.jpg", alt: "pescini Daniela 03-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-029.jpg", alt: "conchiglie 2 04-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-030.jpg", alt: "conchiglie 3 03-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-031.jpg", alt: "dentice M Collet 2022" },
      { src: "/images/legnidimare/original/fuori-catalogo-032.jpg", alt: "Po di Goro 2022" },
      { src: "/images/legnidimare/original/fuori-catalogo-033.jpg", alt: "granchi portoghesi" },
      { src: "/images/legnidimare/original/fuori-catalogo-034.jpg", alt: "cuboide 2022" },
      { src: "/images/legnidimare/original/fuori-catalogo-035.jpg", alt: "Orecchini LUCE 06-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-036.jpg", alt: "KINTSUGI mussolo 06-22" },
      { src: "/images/legnidimare/original/fuori-catalogo-037.jpg", alt: "Trottola verde" },
      { src: "/images/legnidimare/original/fuori-catalogo-038.jpg", alt: "Vanessa 2013" },
      { src: "/images/legnidimare/original/fuori-catalogo-039.jpg", alt: "Trottola Natale 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-040.jpg", alt: "Stellatappi 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-041.jpg", alt: "Secchiello termico 2020" },
      { src: "/images/legnidimare/original/fuori-catalogo-042.jpg", alt: "Ricciotappi 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-043.jpg", alt: "Riccio dorato 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-044.jpg", alt: "Ricci Natale 2020" },
      { src: "/images/legnidimare/original/fuori-catalogo-045.jpg", alt: "Portatovagliolo coppia 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-046.jpg", alt: "Orologio 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-047.jpg", alt: "Pollaio verticale 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-048.jpg", alt: "Orecchini Galuchat 2015" },
      { src: "/images/legnidimare/original/fuori-catalogo-049.jpg", alt: "Orecchini 2021 beneficienza" },
      { src: "/images/legnidimare/original/fuori-catalogo-050.jpg", alt: "Orecchini oro 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-051.jpg", alt: "Orecchini conchiglia 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-052.jpg", alt: "Orecchini lobo 2020" },
      { src: "/images/legnidimare/original/fuori-catalogo-053.jpg", alt: "Libellula 2020" },
      { src: "/images/legnidimare/original/fuori-catalogo-054.jpg", alt: "Lampadario ALU Raspanti" },
      { src: "/images/legnidimare/original/fuori-catalogo-055.jpg", alt: "Lampada Sera" },
      { src: "/images/legnidimare/original/fuori-catalogo-056.jpg", alt: "Lampada scorpione 2016" },
      { src: "/images/legnidimare/original/fuori-catalogo-057.jpg", alt: "Lampada rame II" },
      { src: "/images/legnidimare/original/fuori-catalogo-058.jpg", alt: "Lampada rame I" },
      { src: "/images/legnidimare/original/fuori-catalogo-059.jpg", alt: "Lampada gommalacca" },
      { src: "/images/legnidimare/original/fuori-catalogo-060.jpg", alt: "Lampada fish1" },
      { src: "/images/legnidimare/original/fuori-catalogo-061.jpg", alt: "Omaggio Klimt 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-062.jpg", alt: "Keys portachiavi 2016" },
      { src: "/images/legnidimare/original/fuori-catalogo-063.jpg", alt: "gioielli 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-064.jpg", alt: "Gallina trasparente 2019" },
      { src: "/images/legnidimare/original/fuori-catalogo-065.jpg", alt: "Gallina patch 2015" },
      { src: "/images/legnidimare/original/fuori-catalogo-066.jpg", alt: "Gallina ammezzata 2020" },
      { src: "/images/legnidimare/original/fuori-catalogo-067.jpg", alt: "Gallina 2012" },
      { src: "/images/legnidimare/original/fuori-catalogo-068.jpg", alt: "Ramo corallo 2021" },
      { src: "/images/legnidimare/original/fuori-catalogo-069.jpg", alt: "Azuleios 2013" },
      { src: "/images/legnidimare/original/fuori-catalogo-070.jpg", alt: "Alberone bambu" },
    ],
  },
  vetrina: {
    title: "Vetrina",
    eyebrow: "Diario e aggiornamenti",
    intro:
      "La vetrina raccoglie aggiornamenti, mostre, beneficenza e nuove opere di Legni di Mare.",
    body: [
      "RESINANDO AD ARTE, UNUCI Pisa 6 novembre 2025. Le Rose dei venti, beneficenza lampo 2025. Orecchini di Legnidimare.it, Pasqua 2024: da un paio di gemelli degli anni 50 ecco in beneficenza gli orecchini, disponibili su ordinazione in tutte le tonalità.",
      "Il primo arrivato del 2024 è il pesce Riccio, nato nel nuovo atelier pazientemente ricostruito dopo la tromba d’aria. È un pesce non commestibile, anzi velenoso, scelto per la pigmentazione bianco celeste e la forma bombata.",
      "Premio Rotonda 26 agosto - 2 settembre 2023: di sagome appese, di pesci in scatola, di luci, ombre e colori. L’installazione è basata sulla percezione assistita dalla luce di tre pesci realizzati con materiali diversi quali legno, seme e creta.",
      "Personale a Bolgheri 16-21 giugno 2023: una mostra che ha fuso pesci e bijoux in una cornice cromatica finalizzata alla vendita di beneficenza a favore di Piccole Stelle onlus.",
      "Transumanza artistica: dai pesci di legno al bijoux. Il colore continua ad esprimersi su scala più piccola ma non per questo meno creativa.",
    ],
    gallery: [
      { src: "/images/legnidimare/original/vetrina-01.jpg", alt: "orecchini pasqua 24" },
      { src: "/images/legnidimare/original/vetrina-02.jpg", alt: "riccio" },
      { src: "/images/legnidimare/original/vetrina-03.jpg", alt: "rotonda invito" },
      { src: "/images/legnidimare/original/vetrina-04.jpg", alt: "sagome2" },
      { src: "/images/legnidimare/original/vetrina-05.jpg", alt: "onoff" },
      { src: "/images/legnidimare/original/vetrina-06.jpg", alt: "locandina bolgheri s" },
      { src: "/images/legnidimare/original/vetrina-07.jpg", alt: "bolghri io2" },
      { src: "/images/legnidimare/original/vetrina-08.jpg", alt: "transumanza1" },
      { src: "/images/legnidimare/original/vetrina-09.png", alt: "rossetto1" },
      { src: "/images/legnidimare/original/vetrina-10.png", alt: "rossetto" },
      { src: "/images/legnidimare/original/vetrina-11.png", alt: "rossetto3" },
      { src: "/images/legnidimare/original/vetrina-12.png", alt: "rossetto4" },
      { src: "/images/legnidimare/original/vetrina-13.png", alt: "granchio 1" },
      { src: "/images/legnidimare/original/vetrina-14.png", alt: "granchio2" },
      { src: "/images/legnidimare/original/vetrina-15.png", alt: "granchio3" },
    ],
  },
} as const
